//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicToe.Infinite.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicToe.Infinite.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string AppShell_Dashboard {
            get {
                return ResourceManager.GetString("AppShell_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        internal static string AppShell_Game {
            get {
                return ResourceManager.GetString("AppShell_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tic Tac Toe.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Games: .
        /// </summary>
        internal static string DashboardPage_TotalGames {
            get {
                return ResourceManager.GetString("DashboardPage_TotalGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first.
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable AI (O).
        /// </summary>
        internal static string MainPage_EnableAI {
            get {
                return ResourceManager.GetString("MainPage_EnableAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0}&apos;s Turn!.
        /// </summary>
        internal static string MainPage_PlayersTurn {
            get {
                return ResourceManager.GetString("MainPage_PlayersTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} Wins!.
        /// </summary>
        internal static string MainPage_PlayerWins {
            get {
                return ResourceManager.GetString("MainPage_PlayerWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Game.
        /// </summary>
        internal static string MainPage_ResetGame {
            get {
                return ResourceManager.GetString("MainPage_ResetGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Moves.
        /// </summary>
        internal static string MovesChart_AverageMoves {
            get {
                return ResourceManager.GetString("MovesChart_AverageMoves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Moves.
        /// </summary>
        internal static string MovesChart_TotalMoves {
            get {
                return ResourceManager.GetString("MovesChart_TotalMoves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to third.
        /// </summary>
        internal static string Third {
            get {
                return ResourceManager.GetString("Third", resourceCulture);
            }
        }
    }
}
